name: train_env

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.2
  - pip

  - click==8.1.3
  - joblib==1.1.0
  - pandas==1.4.2
  - scikit-learn==1.0.2

  - pip:
    - azureml-defaults==1.41.0
