channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.2
  - pip

  - click==7.1.2
  - joblib==0.14.1
  - pandas==1.1.4
  - requests==2.23.0
  - scikit-learn==0.22.2.post1
  - packaging


  - pip:
    - azureml-defaults==1.41.0
