name: my_package
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.2
  - pip

  # Model dependencies.
  - click==7.1.2
  - joblib==0.14.1
  - pandas==1.1.4
  - scikit-learn==0.22.2.post1

  # Dev dependencies.
  - pre-commit
  - pytest==5.4.1
  - pytest-cov
  - pytest-lazy-fixture
  - responses
  - pylint==2.5.3
  - black==20.8b1
  - faker==4.1.1

  # For notebooks.
  # - jupyterlab

  - pip:
    # Model dependencies.
    - azureml-defaults==1.41.0
    - azureml-pipeline==1.41.0
    - azure-storage-blob==2.1.0

    # Dev dependencies.
    - pytest-helpers-namespace
    - pytest-mock
    - pep517
    - wheel
